version: '2'
services:
    tg24h-mongodb:
        container_name: tg24h-mongodb
        image: mongo:3.3.5
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/tg24h/mongodb/:/data/db/
